apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2021-09-28T01:05:51Z"
  generation: 1
  name: jaeger-operator
  namespace: observability
  resourceVersion: "27295"
  selfLink: /apis/apps/v1/namespaces/observability/deployments/jaeger-operator
  uid: 124bfdd9-c1ca-492c-a8dc-f3f8e4d9eb90
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: jaeger-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: jaeger-operator
    spec:
      containers:
      - args:
        - start
        env:
        - name: WATCH_NAMESPACE
          value: ""
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: OPERATOR_NAME
          value: jaeger-operator
        image: jaegertracing/jaeger-operator:1.25.0
        imagePullPolicy: Always
        name: jaeger-operator
        ports:
        - containerPort: 8383
          name: http-metrics
          protocol: TCP
        - containerPort: 8686
          name: cr-metrics
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: jaeger-operator
      serviceAccountName: jaeger-operator
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-09-28T01:05:51Z"
    lastUpdateTime: "2021-09-28T01:07:06Z"
    message: ReplicaSet "jaeger-operator-dbf5767c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-10-01T17:15:55Z"
    lastUpdateTime: "2021-10-01T17:15:55Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
