apiVersion: apps/v1
kind: Deployment
metadata:
  name: trial
  labels:
    app: trial
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: trial
  template:
    metadata:
      labels:
        app: trial
    spec:
      containers:
        - name: trial
          image: ualali/metrics-dashboard-trial:latest
          imagePullPolicy: Always
          ports:
            - name: trialport
              containerPort: 8080
              protocol: TCP
