
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "opensuse/Leap-15.2.x86_64"
  config.vm.box_version = "15.2.31.570"

  # Create a forwarded port mapping which allows access to a specific port
  # within the virtual machine from a port on the host machine.
  # NOTE: This will enable public access to the opened port
  config.vm.network "forwarded_port", guest: 3000, host: 3000
  config.vm.network "forwarded_port", guest: 6443, host: 6443
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 8081, host: 8081
  config.vm.network "forwarded_port", guest: 8082, host: 8082
  config.vm.network "forwarded_port", guest: 9090, host: 9090
  config.vm.network "forwarded_port", guest: 16686, host: 16686

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: "192.168.33.10"

  # Create a virtual machine with the specified provider and configuration.
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.name = "k3s"
  end

  # Install necessary software to provide the virtual machine.
  config.vm.provision "apparmor", type: "shell",
    inline: "sudo zypper --non-interactive install -t pattern apparmor"

  config.vm.provision "k3s", type: "shell",
    path: "scripts/k3s.sh"
end
